### ISSUE TITLE
Sound Delay  between AppleTV and Hompod Mini

### ISSUE THREAD

**Issue by Timo35** [LLukas22/Jellyswarrm#46]
I use the Jellyfin app (Version 1.0.1)  on AppleTV and 2 Apple HomePods Mini for audio.

In the player is a experimentall section, where i can switch on the _native player_ to get video/sound in sync. This works for a direct connection to my local and remote (via VPN) Jellyfin Server. 

If i try this thru jellyswarrm, it doesn't work.
Without the native player Option, the Video/Sound are not in sync. 

Will this come into jellyswarrm? 

 THX a lot!

**Comment by Timo35** [comment]
Part two log of jellyswarrm: 

`INFO call:call: jellyswarrm_proxy::handlers::common: Tracking play session for item: 2f2dc071-aa35-8217-2bc1-5b3b2b3d0565, server: <Local>
2025-11-14T08:33:14.399132Z  INFO call:call: jellyswarrm_proxy::handlers::common: Tracking play session for item: 2f2dc071-aa35-8217-2bc1-5b3b2b3d0565, server: <Local>
2025-11-14T08:33:14.709218Z  WARN call:call: jellyswarrm_proxy: Upstream server returned error status: 404 Not Found for Request to: http://<Remote-Sitel>:8096/Items/c56808e0467f7df4eb9a3ed837df04b2/Images/primary?maxWidth=400
2025-11-14T08:33:14.712192Z  WARN call:call: jellyswarrm_proxy: Upstream server returned error status: 404 Not Found for Request to: http://<Remote-Sitel>:8096/Items/d0c26f258d50cbcf129cf49785fb75a5/Images/primary?maxWidth=400
2025-11-14T08:33:14.712599Z  WARN call:call: jellyswarrm_proxy: Upstream server returned error status: 404 Not Found for Request to: http://<Remote-Sitel>:8096/Items/2c5b7720c0cbf3a7e3af2432abfd1044/Images/primary?maxWidth=400
2025-11-14T08:33:15.716213Z  INFO call:call: jellyswarrm_proxy::handlers::videos: Found play session for item: 2f2dc071-aa35-8217-2bc1-5b3b2b3d0565, server: <Local>
2025-11-14T08:33:15.716240Z  INFO call:call: jellyswarrm_proxy::handlers::videos: Redirecting to: http://192.168.0.5:8096/videos/2f2dc071-aa35-8217-2bc1-5b3b2b3d0565/master.m3u8?&DeviceId=tvOS_34100C10-1337-40F0-A912-D6A5F0E6CFDF_1763060843.938096&MediaSourceId=2f2dc071aa3582172bc15b3b2b3d0565&VideoCodec=hevc,h264&AudioCodec=aac&AudioStreamIndex=1&SubtitleStreamIndex=4&VideoBitrate=359808000&AudioBitrate=192000&AudioSampleRate=48000&MaxFramerate=25&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&PlaySessionId=531756c223604821b646b4ff653b51fa&ApiKey=c2727e75715e464ea74266c62cced694&TranscodingMaxAudioChannels=6&RequireAvc=false&EnableAudioVbrEncoding=true&Tag=bb77e07017b4dd350d9a0c6e8dc82584&SubtitleMethod=Encode&h264-level=40&h264-videobitdepth=8&h264-profile=main&h264-audiochannels=2&aac-profile=lc&TranscodeReasons=SubtitleCodecNotSupported
2025-11-14T08:33:25.143841Z  INFO call:call: jellyswarrm_proxy::handlers::common: Tracking play session for item: 2f2dc071-aa35-8217-2bc1-5b3b2b3d0565, server: <Local>`

Same App, same login credentials to Jellyswarrm. But, i found one Video, where the stream starts. 
Still request to the Remote Site.
Strange..

**Comment by LLukas22** [comment]
Ok i added a small patch that should fix the errors we saw in the logs. Maybe it also fixes your sound issues 🤔 

You can try the image via the following tag:
```
ghcr.io/llukas22/jellyswarrm:sha-9658c51
```

**Comment by Timo35** [comment]
Tried your Patch, but still the same Issue:

`2025-11-16T14:40:32.289133Z  INFO jellyswarrm_proxy: Loaded configuration: AppConfig { server_id: "0bf5ead24d8b44a2b7d457bc224bdeb9", public_address: "jellyfarrm:3000", server_name: "Jellyswarrm Proxy", host: "0.0.0.0", port: 3000, include_server_name_in_media: true, username: "admin", password: "swordfish", preconfigured_servers: [], session_key: [107, 69, 20, 184, 16, 230, 157, 171, 64, 235, 3, 103, 25, 160, 221, 199, 38, 76, 42, 209, 42, 138, 182, 244, 215, 192, 97, 80, 151, 18, 189, 199, 238, 160, 116, 250, 233, 241, 225, 146, 159, 60, 241, 228, 105, 141, 64, 89, 222, 73, 79, 215, 65, 190, 27, 191, 239, 51, 176, 115, 96, 198, 130, 221], timeout: 20, ui_route: UrlSegment("ui"), url_prefix: None }
2025-11-16T14:40:32.299065Z  INFO jellyswarrm_proxy: Found 2 configured servers
2025-11-16T14:40:32.299094Z  INFO jellyswarrm_proxy:   Timo (http://192.168.0.5:8096/): priority 100
2025-11-16T14:40:32.299100Z  INFO jellyswarrm_proxy:   Elias (http://<Remote-Site>:8096/): priority 95
2025-11-16T14:40:32.302490Z  INFO jellyswarrm_proxy: No URL prefix configured, using root path
2025-11-16T14:40:32.302528Z  INFO jellyswarrm_proxy: Starting reverse proxy on http://0.0.0.0:3000
2025-11-16T14:40:32.302535Z  INFO jellyswarrm_proxy: UI Management routes available at: http://0.0.0.0:3000/ui
2025-11-16T14:41:43.920076Z ERROR call:call: jellyswarrm_proxy::handlers::common: JSON parsing failed: missing field `Id` at line 85 column 1
At line 85, column 1:
      82 |     }
      83 |   ],
      84 |   "Tags": []
>>>   85 | }
         | ^ (column 1)

2025-11-16T14:41:43.920204Z ERROR call:call: jellyswarrm_proxy::handlers::items: Failed to get MediaItem: 502
2025-11-16T14:41:43.920281Z ERROR call:call: tower_http::trace::on_failure: response failed classification=Status code: 502 Bad Gateway latency=287 ms
2025-11-16T14:41:45.059058Z ERROR call:call: jellyswarrm_proxy::handlers::common: JSON parsing failed: missing field `Id` at line 85 column 1
At line 85, column 1:
      82 |     }
      83 |   ],
      84 |   "Tags": []
>>>   85 | }
         | ^ (column 1)

2025-11-16T14:41:45.059127Z ERROR call:call: jellyswarrm_proxy::handlers::items: Failed to get MediaItem: 502
2025-11-16T14:41:45.059170Z ERROR call:call: tower_http::trace::on_failure: response failed classification=Status code: 502 Bad Gateway latency=1427 ms
2025-11-16T14:41:45.207328Z ERROR call:call: jellyswarrm_proxy::handlers::common: JSON parsing failed: missing field `Id` at line 85 column 1
At line 85, column 1:
      82 |     }
      83 |   ],
      84 |   "Tags": []
>>>   85 | }
         | ^ (column 1)

2025-11-16T14:41:45.207577Z ERROR call:call: jellyswarrm_proxy::handlers::items: Failed to get MediaItem: 502
2025-11-16T14:41:45.207629Z ERROR call:call: tower_http::trace::on_failure: response failed classification=Status code: 502 Bad Gateway latency=1285 ms
2025-11-16T14:41:47.083099Z  WARN call:call: jellyswarrm_proxy: Upstream server returned error status: 404 Not Found for Request to: http://192.168.0.5:8096/Items/58194bdf0986e4190d606cd3560b92d5/Images/thumb?maxWidth=700
2025-11-16T14:41:47.292540Z  WARN call:call: jellyswarrm_proxy: Upstream server returned error status: 404 Not Found for Request to: http://192.168.0.5:8096/Items/58194bdf0986e4190d606cd3560b92d5/Images/backdrop?maxWidth=700
2025-11-16T14:41:47.331965Z ERROR call:call: jellyswarrm_proxy::handlers::common: JSON parsing failed: missing field `Id` at line 85 column 1
At line 85, column 1:
      82 |     }
      83 |   ],
      84 |   "Tags": []
>>>   85 | }
         | ^ (column 1)

2025-11-16T14:41:47.332725Z ERROR call:call: jellyswarrm_proxy::handlers::items: Failed to get MediaItem: 502
2025-11-16T14:41:47.332842Z ERROR call:call: tower_http::trace::on_failure: response failed classification=Status code: 502 Bad Gateway latency=171 ms
2025-11-16T14:41:56.973684Z ERROR call:call: jellyswarrm_proxy::handlers::common: JSON parsing failed: missing field `Id` at line 73 column 1
At line 73, column 1:
      70 |     }
      71 |   ],
      72 |   "Tags": []
>>>   73 | }
         | ^ (column 1)

2025-11-16T14:41:56.973736Z ERROR call:call: jellyswarrm_proxy::handlers::items: Failed to get MediaItem: 502
2025-11-16T14:41:56.973769Z ERROR call:call: tower_http::trace::on_failure: response failed classification=Status code: 502 Bad Gateway latency=878 ms
2025-11-16T14:41:57.509642Z ERROR call:call: jellyswarrm_proxy::handlers::common: JSON parsing failed: missing field `Id` at line 77 column 1
At line 77, column 1:
      74 |     }
      75 |   ],
      76 |   "Tags": []
>>>   77 | }
         | ^ (column 1)

2025-11-16T14:41:57.509725Z ERROR call:call: jellyswarrm_proxy::handlers::items: Failed to get MediaItem: 502
2025-11-16T14:41:57.509762Z ERROR call:call: tower_http::trace::on_failure: response failed classification=Status code: 502 Bad Gateway latency=54 ms
2025-11-16T14:41:57.676929Z ERROR call:call: jellyswarrm_proxy::handlers::common: JSON parsing failed: missing field `Id` at line 49 column 1
At line 49, column 1:
      46 |     }
      47 |   ],
      48 |   "Tags": []
>>>   49 | }
         | ^ (column 1)

2025-11-16T14:41:57.676980Z ERROR call:call: jellyswarrm_proxy::handlers::items: Failed to get MediaItem: 502
2025-11-16T14:41:57.677013Z ERROR call:call: tower_http::trace::on_failure: response failed classification=Status code: 502 Bad Gateway latency=41 ms
2025-11-16T14:42:05.199034Z ERROR call:call: jellyswarrm_proxy::handlers::common: JSON parsing failed: missing field `Id` at line 73 column 1
At line 73, column 1:
      70 |     }
      71 |   ],
      72 |   "Tags": []
>>>   73 | }
         | ^ (column 1)

2025-11-16T14:42:05.199081Z ERROR call:call: jellyswarrm_proxy::handlers::items: Failed to get MediaItem: 502
2025-11-16T14:42:05.199126Z ERROR call:call: tower_http::trace::on_failure: response failed classification=Status code: 502 Bad Gateway latency=14 ms
2025-11-16T14:42:10.713298Z  WARN call:call: jellyswarrm_proxy: Upstream server returned error status: 404 Not Found for Request to: http://192.168.0.5:8096/Items/9298f63e1ae917e58fe8ab07044767fd/Images/primary?maxWidth=400
2025-11-16T14:42:10.717057Z  WARN call:call: jellyswarrm_proxy: Upstream server returned error status: 404 Not Found for Request to: http://192.168.0.5:8096/Items/b0102ea52093609dc855b1c8ab58119c/Images/primary?maxWidth=400
2025-11-16T14:42:10.721431Z  WARN call:call: jellyswarrm_proxy: Upstream server returned error status: 404 Not Found for Request to: http://192.168.0.5:8096/Items/d682c9fde387c72e963df66cf1a862ac/Images/primary?maxWidth=400
2025-11-16T14:42:10.721612Z  WARN call:call: jellyswarrm_proxy: Upstream server returned error status: 404 Not Found for Request to: http://192.168.0.5:8096/Items/41e7206092fbbd2f0ec84febd36a6b55/Images/primary?maxWidth=400
2025-11-16T14:42:12.594752Z ERROR call:call: jellyswarrm_proxy::handlers::videos: No play session found for resource: 6be5126b62304352838cd1c4b88602b7
2025-11-16T14:42:13.607147Z ERROR call:call: jellyswarrm_proxy::handlers::videos: No play session found for resource: 6be5126b62304352838cd1c4b88602b7
2025-11-16T14:42:15.618838Z ERROR call:call: jellyswarrm_proxy::handlers::videos: No play session found for resource: 6be5126b62304352838cd1c4b88602b7
2025-11-16T14:42:18.638088Z ERROR call:call: jellyswarrm_proxy::handlers::videos: No play session found for resource: 6be5126b62304352838cd1c4b88602b7
2025-11-16T14:42:22.658979Z ERROR call:call: jellyswarrm_proxy::handlers::videos: No play session found for resource: 6be5126b62304352838cd1c4b88602b7
2025-11-16T14:42:27.676902Z ERROR call:call: jellyswarrm_proxy::handlers::videos: No play session found for resource: 6be5126b62304352838cd1c4b88602b7
2025-11-16T14:42:32.693655Z ERROR call:call: jellyswarrm_proxy::handlers::videos: No play session found for resource: 6be5126b62304352838cd1c4b88602b7
2025-11-16T14:42:37.714710Z ERROR call:call: jellyswarrm_proxy::handlers::videos: No play session found for resource: 6be5126b62304352838cd1c4b88602b7
2025-11-16T14:42:42.733750Z ERROR call:call: jellyswarrm_proxy::handlers::videos: No play session found for resource: 6be5126b62304352838cd1c4b88602b7
`

**Comment by Timo35** [comment]
Sure, we can test it, this the minimum i can do for you. :-) 

So, i tried via Browser login to jellyswarrm. I can play any movie. 
To answer your question about the metadata providers. I'm not sure, if my son (remote-side) is using something like this, but on my local side, there a just the following Plug-ins installed and active: AudioDB; MusicBrainz; OMDb; Studio Images; TMDb and Transcode Killer. 

Here the log, when i use the Browser to jellyswarrm: 

`2025-11-16T16:41:21.055946Z  INFO call:call: jellyswarrm_proxy::handlers::users: Attempting authentication for user 'Timo' across 2 servers
2025-11-16T16:41:21.059213Z  INFO call:call: jellyswarrm_proxy::handlers::users: Using server mapping for user 'Timo' on server 'Timo'
2025-11-16T16:41:21.059273Z  INFO call:call: jellyswarrm_proxy::handlers::users: Using server mapping for user 'Timo' on server 'Elias'
2025-11-16T16:41:21.060141Z  INFO jellyswarrm_proxy::handlers::users: Authenticating user 'Timo' at server 'Timo' (http://192.168.0.5:8096/Users/AuthenticateByName)
2025-11-16T16:41:21.060166Z  INFO jellyswarrm_proxy::handlers::users: Authenticating user 'Timo' at server 'Elias' (http://<Remote-Side>:8096/Users/AuthenticateByName)
2025-11-16T16:41:21.401390Z  INFO jellyswarrm_proxy::user_authorization_service: Stored authorization session for user 15a1e257bbfe496f85862393bdf64e4c on server http://192.168.0.5:8096/
2025-11-16T16:41:21.401401Z  INFO jellyswarrm_proxy::handlers::users: Successfully authenticated user 'Timo' on server 'Timo' and stored authorization data with token: dbcadb8ce2f34c39853e23880ac2a65d
2025-11-16T16:41:21.402017Z  INFO call:call: jellyswarrm_proxy::handlers::users: Successfully authenticated user: Timo
2025-11-16T16:41:21.415016Z  INFO jellyswarrm_proxy::user_authorization_service: Stored authorization session for user 15a1e257bbfe496f85862393bdf64e4c on server http://<Remote-Side>:8096/
2025-11-16T16:41:21.415026Z  INFO jellyswarrm_proxy::handlers::users: Successfully authenticated user 'Timo' on server 'Elias' and stored authorization data with token: d5dbdd848a10406e8d9391f08e11f2df
2025-11-16T16:41:21.415074Z  INFO call:call: jellyswarrm_proxy::handlers::users: Successfully authenticated user: Timo
2025-11-16T16:41:21.415084Z  INFO call:call: jellyswarrm_proxy::handlers::users: User 'Timo' successfully authenticated on 2 out of 2 servers and stored in authorization storage
2025-11-16T16:41:21.448099Z  WARN call:call: jellyswarrm_proxy: Upstream server returned error status: 404 Not Found for Request to: http://192.168.0.5:8096/socket?api_key=c2727e75715e464ea74266c62cced694&deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjoxNDUuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC8xNDUuMHwxNzYyOTczMjY5NzIz
2025-11-16T16:41:21.629473Z ERROR jellyswarrm_proxy::handlers::common: Request failed with status: HTTP status client error (403 Forbidden) for url (http://<Remote-Side>:8096/LiveTv/Programs/Recommended?userId=ec4b283551264e7f9a913edee844cf06&IsAiring=true&limit=1&ImageTypeLimit=1&EnableImageTypes=Primary%2CThumb%2CBackdrop&EnableTotalRecordCount=false&Fields=ChannelInfo%2CPrimaryImageAspectRatio)
2025-11-16T16:41:21.629512Z ERROR jellyswarrm_proxy::handlers::federated: Failed to get items from server 'Elias': 401
2025-11-16T16:41:27.437689Z  INFO call:call: jellyswarrm_proxy::handlers::common: Tracking play session for item: fa0d7bef-21f2-842f-b4b6-eedba18fc7a5, server: Timo
2025-11-16T16:41:27.741994Z  INFO call:call: jellyswarrm_proxy::handlers::videos: Found play session for item: fa0d7bef-21f2-842f-b4b6-eedba18fc7a5, server: Timo
2025-11-16T16:41:27.742057Z  INFO call:call: jellyswarrm_proxy::handlers::videos: Redirecting to: http://192.168.0.5:8096/videos/fa0d7bef-21f2-842f-b4b6-eedba18fc7a5/master.m3u8?&DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjoxNDUuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC8xNDUuMHwxNzYyOTczMjY5NzIz&MediaSourceId=fa0d7bef21f2842fb4b6eedba18fc7a5&VideoCodec=av1,hevc,h264,vp9&AudioCodec=aac,opus,flac&AudioStreamIndex=1&VideoBitrate=634429579&AudioBitrate=384000&MaxFramerate=23.976025&SegmentContainer=mp4&MinSegments=1&BreakOnNonKeyFrames=True&PlaySessionId=c67ec0911d864bcfbdeee0c7162cd126&ApiKey=dbcadb8ce2f34c39853e23880ac2a65d&TranscodingMaxAudioChannels=2&RequireAvc=false&EnableAudioVbrEncoding=true&Tag=06a72fbdc6c6193d80bc862188241a6c&SubtitleMethod=Encode&h264-level=40&h264-videobitdepth=8&h264-profile=high&av1-profile=main&av1-rangetype=SDR&av1-level=19&vp9-rangetype=SDR&hevc-profile=main,main10&hevc-rangetype=SDR&hevc-level=183&hevc-deinterlace=true&h264-rangetype=SDR&h264-deinterlace=true&TranscodeReasons=AudioCodecNotSupported`

hope this will help you. 

Again: When i use the AppleTV app direct connected to my local Jellyfin Server, i can play all Movies via Native player.
Maybe, i have to test a direct connection to the Remote-Side?

**Comment by Timo35** [comment]
Sorry for the long delay! In the meantime, the issue has been resolved. Looks like it was a player issue.
